## MoveIt-specific simulation settings
#moveit_sim_hw_interface:
#  joint_model_group: controllers_initial_group_
#  joint_model_group_pose: controllers_initial_pose_
## Settings for ros_control control loop
#generic_hw_control_loop:
#  loop_hz: 300
#  cycle_time_error_threshold: 0.01
## Settings for ros_control hardware interface
#hardware_interface:
#  joints:
#    - virtual_joint
#    - base_to_lever_arm
#    - lever_arm_to_digging_arm
#    - left_wheel_joint
#    - right_wheel_joint
#  sim_control_mode: 1  # 0: position, 1: velocity
## Publish all joint states
## Creates the /joint_states topic necessary in ROS
#joint_state_controller:
#  type: joint_state_controller/JointStateController
#  publish_rate: 50
#controller_list:
#  []
#joint_controller:
#  type: position_controllers/JointPositionController
#  joints:
#    - base_to_lever_arm
#    - lever_arm_to_digging_arm
#  gains:
#    base_to_lever_arm:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    lever_arm_to_digging_arm:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1


controller_list:
  - name: joint_position_controller
    action_ns: joint_trajectory_action
    action: follow_joint_trajectory
    type: joint_controller.py
    joints:
      - base_to_lever_arm
      - lever_arm_to_digging_arm
